name: Deploy Docker Image

on:
  push:
    branches:
      - main  # ou la branche que vous souhaitez surveiller pour les déploiements

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: your-dockerhub-username/your-image-name:latest

    - name: Deploy to server
      run: |
        ssh user@your-server 'docker pull your-dockerhub-username/your-image-name:latest && docker stop your-container-name && docker rm your-container-name && docker run -d --name your-container-name your-dockerhub-username/your-image-name:latest'
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
