name: Deploy Docker Image

on:
  push:
    branches:
      - main  # Branche surveillée pour déclencher le workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub with GitHub Token
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_ACTOR }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: spozer/purgatoire-front:1.0.0

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no campus@51.158.101.51 'cd /var/www/html/ && docker compose down && docker pull spozer/purgatoire-front:1.0.0 && docker compose up'
